name: dualy-backend

services:
  postgres:
    container_name: dualy-postgres
    image: postgres:16
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: dualy
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - '5432:5432'
    volumes:
      - dualy-postgres-data:/var/lib/postgresql/data
    networks:
      - dualy-network

volumes:
  dualy-postgres-data:

networks:
  dualy-network:
    driver: bridge